let stockProductos = [
    {id: 1, nombre: "GNEISS 197", cantidad: 1, desc: "Cartucho Gneiss 197 Negro compatible con las impresoras EPSON XP201/ XP211/ XP401/ XP411/ XP702/ WF2532", precio: 400, img: "./assets/img/cartucho.jpg"},
    {id: 2, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 3, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 4, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 5, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 6, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 7, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 8, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 9, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 10, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 11, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 12, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 13, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 14, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 15, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 16, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 17, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 18, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 19, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},
    {id: 20, nombre: "cartucho", cantidad: 1, desc: "cartucho gneiss", precio: 2500, img: "./assets/img/cartucho.jpg"},

]